[project]
name = "nautilus-extension-quick-file-hasher"
version = "1.8.5"
description = "Nautilus extension for calculating file hashes."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pycairo>=1.28.0",
    "pygobject>=3.52.3",
    "pygobject-stubs>=2.13.0",
]
