[project]
name = "nautilus-extension-quick-file-hasher"
version = "0.9.9"
description = "Nautilus extension for calculating file hashes."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pygobject-stubs>=2.13.0",
]
